services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,conf,isro
      ZOO_MY_ID: 1
      ZOO_CLIENT_PORT: 2181
      ZOO_TICK_TIME: 2000