spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cache-route
              uri: http://localhost:8081
              predicates:
                - Path=/cache/**